import type { Metadata } from 'next';
import Link from 'next/link';

async function getData() {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts');
  return await response.json();
}

export const metadata: Metadata = {
  title: 'Blog | Create Next App',
  description: 'Generated by create next app',
};

export default async function BlogPage() {
  const posts = await getData();
  return (
    <div>
      <h1>BlogPage</h1>
      <div>
        {posts.map((post: any) => (
          <div key={post.id}>
            <Link href={`/blog/${post.id}`}>{post.id}</Link>
          </div>
        ))}
      </div>
    </div>
  );
}
