import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'About | Create Next App',
  description: 'Generated by create next app',
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <h1>AboutPage</h1>
      <header>
        <Link href="/about/team">Team</Link>
        <Link href="/about/contacts">Contacts</Link>
      </header>
      {children}
    </div>
  );
}
