import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Contacts | Create Next App',
  description: 'Generated by create next app',
};

export default function ContactsPage() {
  return <h1>ContactsPage</h1>;
}
