import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Team | Create Next App',
  description: 'Generated by create next app',
};

export default function TeamPage() {
  return <h1>TeamPage</h1>;
}
