export type FinanceTransactionListT = ProxyServerApiDefinitions.Components.Schemas.FinanceTransactionListReport;

export type FinanceTransactionListOperationT = ProxyServerApiDefinitions.Components.Schemas.FinanceTransactionListOperation;
